### ISSUE TITLE
Broken install from folder

### ISSUE THREAD

**Issue by phproberto** [redCOMPONENT-COM/redCORE#426]
## How to reproduce the issue

In joomla select `Extensions` > `Extension Manager` > `Install` > `Install from Directory` and paste there the route to your `redCORE` folder. 

Click install and you will receive an error like:

![redcore](https://cloud.githubusercontent.com/assets/1119272/6820470/9e04ada4-d2cf-11e4-9b1c-017ae8f0bf8d.png)

## More information 

I tracked the bug and is related to https://github.com/redCOMPONENT-COM/redCORE/commit/df3151cec20dd0f83f0211ffadb000c004d4f760 which actually was trying to fix the installer.

I cannot propose a patch as @Kixo didn't add any information about what's being fixed in the PR (see https://github.com/redCOMPONENT-COM/redCORE/pull/339 ).

**Comment by puneet0191** [comment]
@phproberto Try to update the submodule for mvcoverrides, we got this working.

**Comment by phproberto** [comment]
Seems to work @puneet0191. The code still looks wrong though. Thanks!
