### ISSUE TITLE
Plugin breaks modal popup windows

### ISSUE THREAD

**Issue by Jinobix** [redCOMPONENT-COM/redCORE#563]
I have narrowed it down to when the below is enabled:
redCORE - System plugin     Site 		Plugin 	1.5.0 	August 2014 	redCOMPONENT 	system 	

It prevents popup windows on Joomla administrator. (Example: Selecting a menu item type*) 
More details here:
https://github.com/joomla/joomla-cms/issues/7525

Please respond

**Comment by javigomez** [comment]
Please paste here the version of redCORE that you are using. You can find it in the right menu:

<img width="260" alt="screen shot 2015-07-22 at 18 49 24" src="https://cloud.githubusercontent.com/assets/1375475/8831248/71ab17c2-30a1-11e5-8868-3174a4edae8b.png">

**Comment by Jinobix** [comment]
redCORE v1.5.0

**Comment by javigomez** [comment]
Please use the .zip package available at https://github.com/redCOMPONENT-COM/redCORE/releases/tag/1.6.0 to install the new version 1.6.0.

I have just tested and I'm able to open iframes in administrator with current version. 

I'm closing this issue. Please reopen if you have any problem.

thanks


cc: @ot2sen

**Comment by Jinobix** [comment]
I installed v1.60
The problem is still there.

**Comment by javigomez** [comment]
Please @Jinobix  contact our support team http://redcomponent.com/support/ so we can check in deep the issue.

Thanks

**Comment by Jinobix** [comment]
I created an account in order to contact the support team (Create a ticket) and was hit with this message.

"In order to be able to create tickets you need to buy a subscription."

Are you serious?

**Comment by jatitoam** [comment]
The latest version fixes the problem, but it has not been officially released.
However, you can just use the latest code from the repository or simply apply the changes in these files https://github.com/redCOMPONENT-COM/redCORE/pull/546/files

**Comment by javigomez** [comment]
Sorry, I thought you had one of our products using redCORE therefore you have a subscription.

I have created a beta package with @jatitoam addition available in .zip at https://github.com/javigomez/redCORE/releases/tag/1.6.25beta

Please download it from there and install, and confirm that fixes the issue.

thanks very much

**Comment by Jinobix** [comment]
Fixed :+1: 
Thank you
