### ISSUE TITLE
Conflicting with backend of website

### ISSUE THREAD

**Issue by SimREVS** [redCOMPONENT-COM/redCORE#575]
Hi

The redcore system pluging is conflicting in backend on joomla. Its either a jquery or mootools conflict, i've tried jquery easy but to no avail. If i turn pluging off all is well.

Any ideas?

Cheers

Steve

**Comment by jatitoam** [comment]
We had that problem some time ago but it was resolved recently.  Can you try with the latest release?  Or which version are you using?

**Comment by SimREVS** [comment]
i have the latest version i think - i'm running TRACKS by Julien Vonthron

Have you got a link to new version just in case?

Cheers

Steve

**Comment by julienV** [comment]
Hi Steve, are you on joomla 2.5 or 3.x 
i can try to update redcore version in tracks, see if it works better.

**Comment by SimREVS** [comment]
joomla 3

**Comment by SimREVS** [comment]
www.revs-simracing.co.uk

**Comment by julienV** [comment]
if you want send me an email at julien@redweb.dk, i'll mail you an updated redcore version

**Comment by SimREVS** [comment]
Ok thanks

**Comment by SimREVS** [comment]
Thank you so much for helping me out with this issue :)
