### ISSUE TITLE
i cant edit an existing article in joomla

### ISSUE THREAD

**Issue by Frog65** [redCOMPONENT-COM/redCORE#705]
i can open an existing article in joomla 
i can edit the content

but i cant save or close the article...
nothing work...

i had to close the browser tab and opened the joomla admin and **deactivate**
**## redCORE - System plugin**

then i can edit the article as usual.

maybe connected to another fail where posted here ...
https://github.com/redCOMPONENT-COM/redCORE/issues/687

thanks for help...

**Comment by Kixo** [comment]
Hi @Frog65 Can you please update your redCORE version to the latest stable version 1.8.6 You can find it here: https://github.com/redCOMPONENT-COM/redCORE/releases/tag/1.8.6

**Comment by Frog65** [comment]
hi kixo,

i installed the newest version 1.8.6 on my joomla 3.5.1.
i choose "upload package file" under extensions.
after install i get the follow message:
https://abload.de/img/redcore_186_paketinst62uws.jpg
under "extensions"/"manage" now standing:
https://abload.de/img/redcore_186_admins5uuo.jpg

i still can not change edit an existing artice ... 
again behave the same ...

frog

**Comment by Frog65** [comment]
now i have a great problem!!!

i cant edit **custom**-modules...

when i klick to edit an custom-modules i get an error:
https://abload.de/img/custom_modulesvns9u.jpg
https://abload.de/img/custom_modules_errorhcs6q.jpg

ok. i have deactivated red-core systems. but when i not deactivated ... nothing i happened. i opened the custom-modules but i cant close, save or save-close ...

i dont know what i have to do.!!!!!!!!!!!!!!!!!!!

**Comment by julienV** [comment]
Hi Frog,

please try to disable tracks content plugin, it must be the one trying and failing to load.

**Comment by Frog65** [comment]
hi julienV

after i deactivated all Tracks modules, components and so on, i could work normaly.

where is the problem now?

frog

**Comment by julienV** [comment]
Hi Frog, i sent you an email to a.frog@gmx.net, please check it out

**Comment by Frog65** [comment]
many thanks to julien v. for help
the error is eliminated
