### ISSUE TITLE
when i started redCore i get a error message

### ISSUE THREAD

**Issue by Frog65** [redCOMPONENT-COM/redCORE#706]
When i start "redCore - component" under components i get this error message:

1146 Table 'm4351-5.#__redcore_translation_tables' doesn't exist SQL=SELECT `tt`.`translate_columns` AS `columns`,`tt`.`primary_columns` AS `primaryKeys`,`tt`.`fallback_columns` AS `fallbackColumns`,`tt`.`name` AS `table`,`tt`.`title` AS `title`,`tt`.`extension_name` AS `option`,`tt`.`form_links` AS `formLinks` FROM `#__redcore_translation_tables` AS `tt` WHERE tt.state = 1 ORDER BY tt.title

if that oncemore a suberror from this:
https://github.com/redCOMPONENT-COM/redCORE/issues/705

what can i do?

**Comment by Kixo** [comment]
Please update redCORE to latest stable version https://github.com/redCOMPONENT-COM/redCORE/releases/tag/1.8.6

**Comment by Frog65** [comment]
hi kixo,

i installed the newest version 1.8.6 on my joomla 3.5.1.
i choose "upload package file" under extensions.
after install i get the follow message:
https://abload.de/img/redcore_186_paketinst62uws.jpg
under "extensions"/"manage" now standing:
https://abload.de/img/redcore_186_admins5uuo.jpg

the same error message look like on top appear...

frog

**Comment by Frog65** [comment]
many thanks to julien v. for help
the error is eliminated
