### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by quentaro81** [redCOMPONENT-COM/redCORE#881]
Hello!
Error message: "Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/lampp/apps/joomla/htdocs/libraries/redcore/helper/database.php on line 185"
(PHP Version 7.4.5)
Thanks for help!

**Comment by jatitoam** [comment]
heya, this was solved here https://github.com/redCOMPONENT-COM/redCORE/pull/882
thanks for your feedback
