### ISSUE TITLE
RADInput

### ISSUE THREAD

**Issue by quentaro81** [redCOMPONENT-COM/redCORE#884]
I got the following : Error: Class 'RADInput' not found: Class 'RADInput' not found (REDcore 2.0)
Surely this component is wrong. (I just update this, then delete it, and the site working).

5.5.5-10.4.11-MariaDB
utf8mb4_general_ci
PHP | 7.3.17
Apache/2.4.43 (Unix) OpenSSL/1.1.1g PHP/7.3.17 mod_perl/2.0.8-dev Perl/v5.16.3
WebServer to PHP | apache2handler
Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
Joomla!-platform Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by quentaro81** [comment]
Please do something with this error, every time when update the component, i must do it again! 

modify the libraries/redcore/bootstrap.php, add this line of code to line 133

JLoader::registerPrefix('RAD', JPATH_ADMINISTRATOR.'/components/com_eventbooking/libraries/rad');

(before their line of code JLoader::registerPrefix('R', JPATH_REDCORE);) 
(source: https://forum.joomla.org/viewtopic.php?t=949894#p3472471)

**Comment by shandak** [comment]
Hi @quentaro81 ! It's hard to say what is wrong when you are trying to update com_eventbooking. 
Can you please share the error with Joomla debug enabled?
Maybe it would help if you move redCORE system plugin into a different position before or after system `eventbooking` plugin.
It does not sound like redCORE issue. Have you asked for help a team which is developing it?

**Comment by quentaro81** [comment]
Sorry, I will contact EventBooking developers.
